# Hardware bits for "manifold" — ASUS ROG Flow Z13 (GZ302EA).
#   * AMD Ryzen AI Max+ 395 (Strix Halo, Zen 5) + Radeon 8060S (RDNA 3.5 iGPU).
#   * MediaTek MT7925 WiFi 7 + Bluetooth.
#   * Single WD PC SN5000S M.2 2230 NVMe.
# Generated by `nixos-generate-config --no-filesystems` on the target and merged
# by hand (disko owns all filesystems/swap; only the hardware bits are kept).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # NVMe + USB HID + storage bits needed in initrd to unlock the ZFS pool.
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
